### ISSUE TITLE
Move Formatter to subpackage?

### ISSUE THREAD

**Issue by peter-edge** [emicklei/proto#20]
I don't think you can do this if you are following SemVer (which you should!!!), since you already did a 1.0 release (was this intentional), but `Formatter` is a specific implementation on top of the core API, and it would be nice if the root package was just the core API and nothing else. Even nicer would be if the binaries moved outside of this repository into a `proto-contrib` or similar. Nicer on top of that would be if this was named something other than `proto` since that overlaps with github.com/gogo/protobuf/proto, but hey, can't get greedy :-)

All just suggestions.

**Comment by emicklei** [comment]
well, you know how some of these project start. The initial goal was getting a formatter. So a lot of private methods were added to the types. Quite an effort to get it out. I do like the fact that it is part of (a) library instead of putting it all in a command. I will give it some thought, extracting the Formatter.

And about the commands, yes, another thing that has grown to the package. One benefit is that we keep them in sync with the package and users can see actual examples of using it. Maybe if we start getting 5+ commands it needs attention again.

**Comment by peter-edge** [comment]
Perhaps eventually, once this repository is in a more stable state, we could make a proper GitHub organization for it, something like github.com/protoparse or similar, and then have github.com/protoparse/protoparse, github.com/protoparse/protoparse-contrib? We can cut a proper 1.0 then as well?

**Comment by peter-edge** [comment]
I think this really should happen, especially as the built-in formatter is very opinionated. I'm actually building my own formatter, for example.

Additionally, the Formatter replies on private methods on various Visitees - these methods should be made public and their use explained, or they should be removed and made just part of the formatter (which given their purpose is probably a better idea).

**Comment by emicklei** [comment]
I agree that the package should allow for other to create formatters. Opinionated will all of them be. I never got the feedback that the format produced was not satisfactory. The style is close to what some of the Google definitions were written in. For us having a consistent layout is important and it saves useless dev time rearranging syntax.

**Comment by emicklei** [comment]
i started working on https://github.com/emicklei/proto-contrib to which everything but the core package will move to
